ResortPlay/Areas/Dashboard/ViewModels/AccomodationViewModels.cs
using ResortPlay.Entity;
using ResortPlay.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ResortPlay.Areas.Dashboard.ViewModels
{
    public class AccomodationListingModel
    {
        public IEnumerable<Accomodation> Accomodations { get; set; }

        public int? AccomodationPackageId { get; set; }
        public IEnumerable<AccomodationPackage> AccomodationPackages { get; set; }
        public string SearchTerm { get; set; }

        public Pager Pager { get; set; }

    }
    public class AccomodationActionModel
    {
        public int Id { get; set; }

        public int AccomodationPackageId { get; set; }
        public AccomodationPackage AccomodationPackage { get; set; }

        public string Name { get; set; }
        public string Description { get; set; }

        public IEnumerable<AccomodationPackage> AccomodationPackages { get; set; }

    }
}

ResortPlay/Areas/Dashboard/Controllers/AccomodationController.cs
using ResortPlay.Areas.Dashboard.ViewModels;
using ResortPlay.Entity;
using ResortPlay.ViewModels;
using Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ResortPlay.Areas.Dashboard.Controllers
{
    public class AccomodationController : Controller
    {
        AccomodationsService accomodationsService = new AccomodationsService();
        AccomodationPackagesService accomodationPackagesService = new AccomodationPackagesService();

        public ActionResult Index(string searchTerm, int? accomodationPackageId, int? page) //search by seartchterm and accomodation package by its id. Only gets int.  // The int page is for the pages each with 3 packages
        {
            //how much accomodations will show at a time
            int recordSize = 3;
            page = page ?? 1;

            AccomodationListingModel model = new AccomodationListingModel();
            //Word search
            model.SearchTerm = searchTerm;
            //Type search
            model.AccomodationPackageId = accomodationPackageId;

            model.Accomodations = accomodationsService.SearchAccomodations(searchTerm, accomodationPackageId, page.Value, recordSize);
            model.AccomodationPackages = accomodationPackagesService.GetAllAccomodationPackages();

            //The pager controller
            var totalRecords = accomodationsService.SearchAccomodationsCount(searchTerm, accomodationPackageId);
            model.Pager = new Pager(totalRecords, page, recordSize);
            return View(model);
        }

        //Here to Read from the model the chosen accomodation
        [HttpGet]
        public ActionResult Action(int? Id)
        {
            AccomodationActionModel model = new AccomodationActionModel();

            if (Id.HasValue) // View the records
            {
                var accomodation = accomodationsService.GetAccomodationById(Id.Value);

                model.Id = accomodation.Id;
                model.AccomodationPackageId = accomodation.AccomodationPackageId;
                model.Name = accomodation.Name;
                model.Description = accomodation.Description;
            }

            model.AccomodationPackages = accomodationPackagesService.GetAllAccomodationPackages();

            return PartialView("_Action", model);
        }
        //Here to make an action on the chosen accomodation
        [HttpPost]
        public JsonResult Action(AccomodationActionModel model)
        {

            JsonResult json = new JsonResult();
            var result = false;

            if (model.Id > 0) //Edit a record
            {
                var accomodation = accomodationsService.GetAccomodationById(model.Id);

                accomodation.AccomodationPackageId = model.AccomodationPackageId;
                accomodation.Name = model.Name;
                accomodation.Description = model.Description;

                result = accomodationsService.EditAccomodation(accomodation);

            }
            else //Create a record
            {

                Accomodation accomodation = new Accomodation();

                accomodation.AccomodationPackageId = model.AccomodationPackageId;
                accomodation.Name = model.Name;
                accomodation.Description = model.Description;

                result = accomodationsService.SaveAccomodation(accomodation);
            }

            if (result)
            {
                json.Data = new { Success = true };
            }
            else
            {
                json.Data = new { Success = false, Message = "Unable to perform action on Accomodation Type." };
            }


            return json;
        }
        //Here is to Delete the accomodation
        [HttpGet]
        public ActionResult Delete(int Id)
        {
            AccomodationActionModel model = new AccomodationActionModel();

            var accomodation = accomodationsService.GetAccomodationById(Id);

            model.Id = accomodation.Id;

            return PartialView("_Delete", model);

        }
        [HttpPost]
        public JsonResult Delete(AccomodationActionModel model)
        {
            JsonResult json = new JsonResult();
            var result = false;

            var accomodation = accomodationsService.GetAccomodationById(model.Id);
            result = accomodationsService.DeleteAccomodation(accomodation);

            if (result)
            {
                json.Data = new { Success = true };
            }
            else
            {
                json.Data = new { Success = false, Message = "Unable to perform action on Accomodation Type." };
            }
            return json;
        }
    }
}

ResortPlay/Areas/Dashboard/Views/Accomodation/Index.cshtml
@model  ResortPlay.Areas.Dashboard.ViewModels.AccomodationListingModel
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="col col-lg-12">
        <h2>Accomodations</h2>
        <hr />
    </div>
</div>
<div class="row mb-3 justify-content-center">
    <div class="col col-lg-8">
        <form>
            <div class="input-group">
                <input type="search" name="searchterm" class="form-control" placeholder="Search for..." value="@Model.SearchTerm">

                @if (Model.AccomodationPackages != null && Model.AccomodationPackages.Count() > 0)
                {
                    <select name="AccomodationPackageId" class="form-control">
                        <option value="0">
                            Select Type..
                        </option>
                        @foreach (var accomodationPackage in Model.AccomodationPackages)
                        {
                            <option value="@accomodationPackage.Id" @(accomodationPackage.Id == Model.AccomodationPackageId ? "selected" : string.Empty)>
                                @accomodationPackage.Name
                            </option>
                        }
                    </select>
                }



                <div class="input-group-append">
                    <button class="btn btn-outline-primary" type="submit"><i class="fa-solid fa-magnifying-glass"></i> Search</button>
                    <a class="btn btn-outline-secondary" href="@Url.Action("Index", "Accomodation")"><i class="fa-solid fa-arrows-rotate"></i></a>
                </div>
                <div class="input-group-append ms-3">
                    <button data-href="@Url.Action("Action", "Accomodation")" type="button" class="data-btn btn btn-success" data-toggle="modal" data-target="#popupWindow">
                        Create <i class="fa-solid fa-plus"></i>
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
<!-- The Partial View of Listing -->

<div class="row">
    <div class="col col-lg-12">
        @{ Html.RenderPartial("_Listing", Model); }
    </div>
</div>



<!-- Popup when click on Create button -->

<div class="modal fade" id="popupWindow" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document"></div>
</div>

<!-- script for the popup windows -->

<script>
    $(".data-btn").click(function () {
        $.ajax({
            url: $(this).attr("data-href"),
        })
            .done(function (response) {
                $("#popupWindow .modal-dialog").html(response);
            });
    });

</script>

ResortPlay/Areas/Dashboard/Views/Accomodation/_Action.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

@model  ResortPlay.Areas.Dashboard.ViewModels.AccomodationActionModel

@if (Model != null)
{
    <div class="modal-content">
        <div class="modal-header">

            <h5 class="modal-title">
                @if (Model.Id > 0)
                {
                    <span>Editing an element</span>
                }
                else
                {
                    <span>Adding an element</span>
                }
            </h5>

            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>

        </div>
        <div class="modal-body">

            <form id="addForm">
                <input type="hidden" name="Id" value="@Model.Id" />
                <div class="form-group">
                    <label>Accomodation Package</label>
                    <select class="form-control" name="AccomodationPackageId">
                        @if (Model.AccomodationPackages != null)
                        {
                            foreach (var accomodationPackage in Model.AccomodationPackages)
                            {
                                <option value="@accomodationPackage.Id" @(accomodationPackage.Id == Model.AccomodationPackageId ? "selected" : string.Empty)>
                                    @accomodationPackage.Name
                                </option>
                            }
                        }
                    </select>
                </div>
                <div class="form-group">
                    <label>Name</label>
                    <input class="form-control" name="Name" placeholder="Enter Name.." value="@Model.Name">
                </div>
                <div class="form-group">
                    <label>Description</label>
                    <textarea class="form-control" name="Description" placeholder="Enter Description..">@Model.Description</textarea>
                </div>
            </form>

            <div class="errorDiv">

            </div>

        </div>
        <div class="modal-footer">
            <button id="addButton" type="button" class="btn btn-primary">Save <i class="fa-regular fa-floppy-disk"></i></button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close <i class="fa-solid fa-xmark"></i></button>
        </div>
    </div>
}


<script>
    $("#addButton").click(function () {
         $.ajax({
             url: '@Url.Action("Action", "Accomodation")',
             type: "post",
             data: $("#addForm").serialize()
        })
             .done(function (response) {

                if (response.Success)
                {
                    //data is saved.. reload listing
                    location.reload();
                }
                else
                {
                    $(".errorDiv").html(response.Message)
                }
            });
    });
</script>

ResortPlay/Areas/Dashboard/Views/Accomodation/_Delete.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

@model  ResortPlay.Areas.Dashboard.ViewModels.AccomodationActionModel

@if (Model != null)
{
    <div class="modal-content">
        <div class="modal-header">

            <h5 class="modal-title">
                <span>Delete Accomodation</span>
            </h5>

            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>

        </div>
        <div class="modal-body">

            <form id="deleteForm">
                <input type="hidden" name="Id" value="@Model.Id" />

                <div class="alert alert-danger" role="alert">
                    Are you sure you want to delete this element?
                </div>

            </form>

        </div>
        <div class="modal-footer">
            <button id="deleteButton" type="button" class="btn btn-danger">Delete  <i class="fa-solid fa-trash-can"></i></button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

        </div>
    </div>
}


<script>
    $("#deleteButton").click(function () {
         $.ajax({
             url: '@Url.Action("Delete", "Accomodation")',
             type: "post",
             data: $("#deleteForm").serialize()
        })
             .done(function (response) {
                if (response.Success)
                {
                    //data is saved.. reload listing
                   window.location.href = "@Url.Action("Index", "Accomodation")";
                }
                else
                {
                    $(".errorDiv").html(response.Message)
                }
            });
    });
</script>

ResortPlay/Areas/Dashboard/Views/Accomodation/_Listing.cshtml
@model ResortPlay.Areas.Dashboard.ViewModels.AccomodationListingModel

@if (Model != null && Model.Accomodations != null && Model.Accomodations.Count() > 0)
{
    <div class="table-responsive-md">
        <table class="table table-striped table-dark table-hover">
            <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Description</th>   
                    <th scope="col">Accomodation Package</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>

                @foreach (var accomodation in Model.Accomodations)
                {
                    <tr>
                        <td>@accomodation.Name</td>
                        <td>@accomodation.Description</td>
                        <td>
                            @if (accomodation.AccomodationPackage != null)
                            {
                                @accomodation.AccomodationPackage.Name
                            }
                        </td>

                        <td>
                            <!--Edit button-->
                            <button data-href="@Url.Action("Action", "Accomodation", new {ID = accomodation.Id })" type="button" class="data-btn btn btn-warning" data-toggle="modal" data-target="#popupWindow" aria-pressed="false" autocomplete="off">
                                Edit <i class="fa-solid fa-pen-nib"></i>
                            </button>
                            <!--Delete button-->
                            <button data-href="@Url.Action("Delete", "Accomodation", new {ID = accomodation.Id })" type="button" class="data-btn btn btn-danger" data-toggle="modal" data-target="#popupWindow" aria-pressed="false" autocomplete="off">
                                Delete <i class="fa-solid fa-trash-can"></i>
                            </button>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    if (Model.Pager.EndPage > 1)
    {
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                @if (Model.Pager.CurrentPage > 1)
                {
                    <li class="page-item">
                        <a class="page-link" href="@Url.Action("Index", "Accomodation")">
                            <i class="fa-solid fa-backward-fast"></i>
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="@Url.Action("Index", "Accomodation", new { page = Model.Pager.CurrentPage - 1, searchTerm = Model.SearchTerm, accomodationPackageId = Model.AccomodationPackageId })">
                            <i class="fa-solid fa-backward"></i>
                        </a>
                    </li>
                }

                @for (var page = Model.Pager.StartPage; page <= Model.Pager.EndPage; page++)
                {
                    <li class="page-item @(page == Model.Pager.CurrentPage ? "active" : "")">
                       <a class="page-link" href="@Url.Action("Index", "Accomodation", new { page = page, searchTerm = Model.SearchTerm, accomodationPackageId = Model.AccomodationPackageId})">@page</a>
                    </li>
                }

                @if (Model.Pager.CurrentPage < Model.Pager.TotalPages)
                {
                    <li class="page-item">
                        <a class="page-link" href="@Url.Action("Index", "Accomodation", new { page = Model.Pager.CurrentPage + 1, searchTerm = Model.SearchTerm, accomodationPackageId = Model.AccomodationPackageId })">
                            <i class="fa-solid fa-forward"></i>
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="@Url.Action("Index", "Accomodation", new { page = Model.Pager.TotalPages, searchTerm = Model.SearchTerm, accomodationPackageId = Model.AccomodationPackageId })">
                            <i class="fa-solid fa-forward-fast"></i>
                        </a>
                    </li>
                }
            </ul>
        </nav>
    }


}

else
{
    <div class="alert alert-warning" role="alert">
        Sorry! No added Accomodation Types yet, please add.
    </div>
}