ResortPlay/Areas/Dashboard/ViewModels/AccomodationPackageViewModels.cs
using ResortPlay.Entity;
using ResortPlay.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ResortPlay.Areas.Dashboard.ViewModels
{
    public class AccomodationPackagesListingModel
    {
        public IEnumerable<AccomodationPackage> AccomodationPackages { get; set; }
        public IEnumerable<AccomodationType> AccomodationTypes { get; set; }
        public string SearchTerm { get; set; }
        public int? AccomodationTypeId { get; set; }

        public Pager Pager { get; set; }
    }
    public class AccomodationPackageActionModel
    {
        public int Id { get; set; }
        public int AccomodationTypeId { get; set; }
        public AccomodationType AccomodationType { get; set; }

        public string Name { get; set; }
        public int NoOfRooms { get; set; }
        public decimal FeePerNight { get; set; }

        public IEnumerable<AccomodationType> AccomodationTypes { get; set; }
    }

}

ResortPlay/Areas/Dashboard/Controllers/AccomodationPackagesController.cs
using ResortPlay.Areas.Dashboard.ViewModels;
using ResortPlay.Entity;
using ResortPlay.ViewModels;
using Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ResortPlay.Areas.Dashboard.Controllers
{
    public class AccomodationPackagesController : Controller
    {
        AccomodationPackagesService accomodationPackagesService = new AccomodationPackagesService();
        AccomodationTypesService accomodationTypesService = new AccomodationTypesService();

        public ActionResult Index(string searchTerm, int? accomodationTypeId, int? page) //search by seartchterm and accomodation type by its id. Only gets int.  // The int page is for the pages each with 3 packages
        {
            //how much packages will show at a time
            int recordSize = 3;
            page = page ?? 1;

            AccomodationPackagesListingModel model = new AccomodationPackagesListingModel();
            //Word search
            model.SearchTerm = searchTerm;
            //Type search
            model.AccomodationTypeId = accomodationTypeId;

            model.AccomodationPackages = accomodationPackagesService.SearchAccomodationPackages(searchTerm, accomodationTypeId, page.Value, recordSize);
            model.AccomodationTypes = accomodationTypesService.GetAllAccomodationTypes();

            //The pager controller
            var totalRecords = accomodationPackagesService.SearchAccomodationPackagesCount(searchTerm, accomodationTypeId);
            model.Pager = new Pager(totalRecords, page, recordSize);
            return View(model);
        }

        //Here to Read from the model the chosen accomodation
        [HttpGet]
        public ActionResult Action(int? Id)
        {
            AccomodationPackageActionModel model = new AccomodationPackageActionModel();

            if (Id.HasValue) // View the records
            {
                var accomodationPackage = accomodationPackagesService.GetAccomodationPackageById(Id.Value);

                model.Id = accomodationPackage.Id;
                model.AccomodationTypeId = accomodationPackage.AccomodationTypeId;
                model.Name = accomodationPackage.Name;
                model.NoOfRooms = accomodationPackage.NoOfRooms;
                model.FeePerNight = accomodationPackage.FeePerNight;

            }

            model.AccomodationTypes = accomodationTypesService.GetAllAccomodationTypes();

            return PartialView("_Action", model);
        }
        //Here to make an action on the chosen accomodation
        [HttpPost]
        public JsonResult Action(AccomodationPackageActionModel model)
        {

            JsonResult json = new JsonResult();
            var result = false;

            if (model.Id > 0) //Edit a record
            {
                var accomodationPackage = accomodationPackagesService.GetAccomodationPackageById(model.Id);

                accomodationPackage.AccomodationTypeId= model.AccomodationTypeId;
                accomodationPackage.Name = model.Name;
                accomodationPackage.NoOfRooms = model.NoOfRooms;
                accomodationPackage.FeePerNight = model.FeePerNight;


                result = accomodationPackagesService.EditAccomodationPackage(accomodationPackage);

            }
            else //Create a record
            {

                AccomodationPackage accomodationPackage = new AccomodationPackage();

                accomodationPackage.AccomodationTypeId = model.AccomodationTypeId;
                accomodationPackage.Name = model.Name;
                accomodationPackage.NoOfRooms = model.NoOfRooms;
                accomodationPackage.FeePerNight = model.FeePerNight;

                result = accomodationPackagesService.SaveAccomodationPackage(accomodationPackage);
            }

            if (result)
            {
                json.Data = new { Success = true };
            }
            else
            {
                json.Data = new { Success = false, Message = "Unable to perform action on Accomodation Type." };
            }


            return json;
        }
        //Here is to Delete the accomodation
        [HttpGet]
        public ActionResult Delete(int Id)
        {
            AccomodationPackageActionModel model = new AccomodationPackageActionModel();

            var accomodationPackage = accomodationPackagesService.GetAccomodationPackageById(Id);

            model.Id = accomodationPackage.Id;

            return PartialView("_Delete", model);

        }
        [HttpPost]
        public JsonResult Delete(AccomodationPackageActionModel model)
        {
            JsonResult json = new JsonResult();
            var result = false;

            var accomodationPackage = accomodationPackagesService.GetAccomodationPackageById(model.Id);
            result = accomodationPackagesService.DeleteAccomodationPackage(accomodationPackage);

            if (result)
            {
                json.Data = new { Success = true };
            }
            else
            {
                json.Data = new { Success = false, Message = "Unable to perform action on Accomodation Type." };
            }
            return json;
        }

    }
}

ResortPlay/Areas/Dashboard/Views/AccomodationPackages/Index.cshtml
@model  ResortPlay.Areas.Dashboard.ViewModels.AccomodationPackagesListingModel
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="col col-lg-12">
        <h2>Accomodation Packages</h2>
        <hr />
    </div>
</div>
<div class="row mb-3">
    <div class="col col-lg-8">
        <form>
            <div class="input-group">
                <input type="search" name="searchterm" class="form-control" placeholder="Search for..." value="@Model.SearchTerm">

                @if (Model.AccomodationTypes != null && Model.AccomodationTypes.Count() > 0)
                {
                    <select name="AccomodationTypeId" class="form-control">
                        <option value="0">
                            Select Type..
                        </option>
                        @foreach (var accomodationType in Model.AccomodationTypes)
                        {
                            <option value="@accomodationType.Id" @(accomodationType.Id == Model.AccomodationTypeId ? "selected" : string.Empty)>
                                @accomodationType.Name
                            </option>
                        }
                    </select>
                }



                <div class="input-group-append">
                    <button class="btn btn-outline-primary" type="submit"><i class="fa-solid fa-magnifying-glass"></i> Search</button>
                    <a class="btn btn-outline-secondary" href="@Url.Action("Index", "AccomodationPackages")"><i class="fa-solid fa-arrows-rotate"></i></a>
                </div>
                <div class="input-group-append ms-3">
                    <button data-href="@Url.Action("Action", "AccomodationPackages")" type="button" class="data-btn btn btn-success" data-toggle="modal" data-target="#popupWindow">
                        Create <i class="fa-solid fa-plus"></i>
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
<!-- The Partial View of Listing -->

<div class="row">
    <div class="col col-lg-12">
        @{ Html.RenderPartial("_Listing", Model); }
    </div>
</div>



<!-- Popup when click on Create button -->

<div class="modal fade" id="popupWindow" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document"></div>
</div>

<!-- script for the popup windows -->

<script>
    $(".data-btn").click(function () {
        $.ajax({
            url: $(this).attr("data-href"),
        })
            .done(function (response) {
                $("#popupWindow .modal-dialog").html(response);
            });
    });

</script>

ResortPlay/Areas/Dashboard/Views/AccomodationPackages/_Action.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

@model  ResortPlay.Areas.Dashboard.ViewModels.AccomodationPackageActionModel

@if (Model != null)
{
    <div class="modal-content">
        <div class="modal-header">

            <h5 class="modal-title">
                @if (Model.Id > 0)
                {
                    <span>Editing an element</span>
                }
                else
                {
                    <span>Adding an element</span>
                }
            </h5>

            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>

        </div>
        <div class="modal-body">

            <form id="addForm">
                <input type="hidden" name="Id" value="@Model.Id" />
                <div class="form-group">
                    <label>Accomodation Type</label>
                    <select class="form-control" name="AccomodationTypeId">
                        @if (Model.AccomodationTypes != null)
                        {
                            foreach (var accomodationType in Model.AccomodationTypes)
                            {
                                <option value="@accomodationType.Id" @(accomodationType.Id == Model.AccomodationTypeId ? "selected" : string.Empty) >
                                    @accomodationType.Name
                                </option>
                            }
                        }
                    </select>
                </div>
                <div class="form-group">
                    <label>Name</label>
                    <input class="form-control" name="Name" placeholder="Enter Name.." value="@Model.Name">
                </div>
                <div class="form-group">
                    <label>Rooms</label>
                    <input class="form-control" name="NoOfRooms" placeholder="Enter number of rooms.." value="@Model.NoOfRooms">
                </div>
                <div class="form-group">
                    <label>Fee per night</label>
                    <input class="form-control" name="FeePerNight" placeholder="Enter fee per night.." value="@Model.FeePerNight">
                </div>
            </form>

            <div class="errorDiv">

            </div>

        </div>
        <div class="modal-footer">
            <button id="addButton" type="button" class="btn btn-primary">Save <i class="fa-regular fa-floppy-disk"></i></button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close <i class="fa-solid fa-xmark"></i></button>
        </div>
    </div>
}


<script>
    $("#addButton").click(function () {
         $.ajax({
             url: '@Url.Action("Action", "AccomodationPackages")',
             type: "post",
             data: $("#addForm").serialize()
        })
             .done(function (response) {

                if (response.Success)
                {
                    //data is saved.. reload listing
                    location.reload();
                }
                else
                {
                    $(".errorDiv").html(response.Message)
                }
            });
    });
</script>

ResortPlay/Areas/Dashboard/Views/AccomodationPackages/_Delete.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

@model  ResortPlay.Areas.Dashboard.ViewModels.AccomodationPackageActionModel

@if (Model != null)
{
    <div class="modal-content">
        <div class="modal-header">

            <h5 class="modal-title">
                <span>Delete Accomodation Package</span>
            </h5>

            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>

        </div>
        <div class="modal-body">

            <form id="deleteForm">
                <input type="hidden" name="Id" value="@Model.Id" />

                <div class="alert alert-danger" role="alert">
                    Are you sure you want to delete this element?
                </div>

            </form>

        </div>
        <div class="modal-footer">
            <button id="deleteButton" type="button" class="btn btn-danger">Delete  <i class="fa-solid fa-trash-can"></i></button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

        </div>
    </div>
}


<script>
    $("#deleteButton").click(function () {
         $.ajax({
             url: '@Url.Action("Delete", "AccomodationPackages")',
             type: "post",
             data: $("#deleteForm").serialize()
        })
             .done(function (response) {
                if (response.Success)
                {
                    //data is saved.. reload listing
                   window.location.href = "@Url.Action("Index", "AccomodationPackages")";
                }
                else
                {
                    $(".errorDiv").html(response.Message)
                }
            });
    });
</script>

ResortPlay/Areas/Dashboard/Views/AccomodationPackages/_Listing.cshtml
@model ResortPlay.Areas.Dashboard.ViewModels.AccomodationPackagesListingModel

@if (Model != null && Model.AccomodationPackages != null && Model.AccomodationPackages.Count() > 0)
{
    <div class="table-responsive-md">
        <table class="table table-striped table-dark table-hover">
            <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Fee per Night</th>
                    <th scope="col">Number of rooms</th>
                    <th scope="col">Accomodation Type</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>

                @foreach (var accomodationPackage in Model.AccomodationPackages)
                {
                    <tr>
                        <td>@accomodationPackage.Name</td>
                        <td>@accomodationPackage.FeePerNight$</td>
                        <td>@accomodationPackage.NoOfRooms</td>
                        <td>
                            @if (accomodationPackage.AccomodationType != null)
                            {
                                @accomodationPackage.AccomodationType.Name
                            }
                        </td>

                        <td>
                            <!--Edit button-->
                            <button data-href="@Url.Action("Action", "AccomodationPackages", new {ID = accomodationPackage.Id })" type="button" class="data-btn btn btn-warning" data-toggle="modal" data-target="#popupWindow" aria-pressed="false" autocomplete="off">
                                Edit <i class="fa-solid fa-pen-nib"></i>
                            </button>
                            <!--Delete button-->
                            <button data-href="@Url.Action("Delete", "AccomodationPackages", new {ID = accomodationPackage.Id })" type="button" class="data-btn btn btn-danger" data-toggle="modal" data-target="#popupWindow" aria-pressed="false" autocomplete="off">
                                Delete <i class="fa-solid fa-trash-can"></i>
                            </button>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    if (Model.Pager.EndPage > 1)
    {
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                @if (Model.Pager.CurrentPage > 1)
                {
                    <li class="page-item">
                        <a class="page-link" href="@Url.Action("Index", "AccomodationPackages")">
                            <i class="fa-solid fa-backward-fast"></i>
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="@Url.Action("Index", "AccomodationPackages", new { page = Model.Pager.CurrentPage - 1, searchTerm = Model.SearchTerm, accomodationTypeID = Model.AccomodationTypeId })">
                            <i class="fa-solid fa-backward"></i>
                        </a>
                    </li>
                }

                @for (var page = Model.Pager.StartPage; page <= Model.Pager.EndPage; page++)
                {
                    <li class="page-item @(page == Model.Pager.CurrentPage ? "active" : "")">
                       <a class="page-link" href="@Url.Action("Index", "AccomodationPackages", new { page = page, searchTerm = Model.SearchTerm, accomodationTypeID = Model.AccomodationTypeId})">@page</a>
                    </li>
                }

                @if (Model.Pager.CurrentPage < Model.Pager.TotalPages)
                {
                    <li class="page-item">
                        <a class="page-link" href="@Url.Action("Index", "AccomodationPackages", new { page = Model.Pager.CurrentPage + 1, searchTerm = Model.SearchTerm, accomodationTypeID = Model.AccomodationTypeId })">
                            <i class="fa-solid fa-forward"></i>
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="@Url.Action("Index", "AccomodationPackages", new { page = Model.Pager.TotalPages, searchTerm = Model.SearchTerm, accomodationTypeID = Model.AccomodationTypeId })">
                            <i class="fa-solid fa-forward-fast"></i>
                        </a>
                    </li>
                }
            </ul>
        </nav>
    }


}

else
{
    <div class="alert alert-warning" role="alert">
        Sorry! No added Accomodation Types yet, please add.
    </div>
}