ResortPlay/Areas/Dashboard/Controllers/AccomodationTypesController.cs
using ResortPlay.Areas.Dashboard.ViewModels;
using ResortPlay.Entity;
using Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ResortPlay.Areas.Dashboard.Controllers
{
    public class AccomodationTypesController : Controller
    {
        AccomodationTypesService accomodationTypesService = new AccomodationTypesService();
        public ActionResult Index(string searchTerm)
        {
            AccomodationTypesListingModel model = new AccomodationTypesListingModel();

            model.SearchTerm = searchTerm;

            model.AccomodationTypes = accomodationTypesService.SearchAccomodationTypes(searchTerm);

            return View(model);
        }
        //Here to Read from the model the chosen accomodation
        [HttpGet]
        public ActionResult Action(int? Id)
        {
            AccomodationTypeActionModel model = new AccomodationTypeActionModel();

            if (Id.HasValue) //Edit a record
            {
                var accomodationType = accomodationTypesService.GetAccomodationTypeById(Id.Value);

                model.Id = accomodationType.Id;
                model.Name= accomodationType.Name;
                model.Description= accomodationType.Description;

            }
            

            return PartialView("_Action", model);


        }
        //Here to make an action on the chosen accomodation
        [HttpPost]
        public JsonResult Action(AccomodationTypeActionModel model)
        {

            JsonResult json = new JsonResult();
            var result = false;

            if (model.Id > 0) //Edit a record
            {
                var accomodationType = accomodationTypesService.GetAccomodationTypeById(model.Id);

                accomodationType.Name= model.Name;
                accomodationType.Description = model.Description;

                result = accomodationTypesService.EditAccomodationTypes(accomodationType);

            }
            else //Create a record
            {

                AccomodationType accomodationType = new AccomodationType();

                accomodationType.Name = model.Name;
                accomodationType.Description = model.Description;

                result = accomodationTypesService.SaveAccomodationTypes(accomodationType);
            }

            if (result)
            {
                json.Data = new {Success = true};
            }
            else
            {
                json.Data = new { Success = false, Message = "Unable to perform action on Accomodation Type." };
            }
            

            return json;
        }
        //Here is to Delete the accomodation
        [HttpGet]
        public ActionResult Delete(int Id)
        {
            AccomodationTypeActionModel model = new AccomodationTypeActionModel();

            var accomodationType = accomodationTypesService.GetAccomodationTypeById(Id);

            model.Id = accomodationType.Id;
         
            return PartialView("_Delete", model);

        }
        [HttpPost]
        public JsonResult Delete(AccomodationTypeActionModel model)
        {
            JsonResult json = new JsonResult();
            var result = false;

            var accomodationType = accomodationTypesService.GetAccomodationTypeById(model.Id);
            result = accomodationTypesService.DeleteAccomodationTypes(accomodationType);

            if (result)
            {
                json.Data = new { Success = true };
            }
            else
            {
                json.Data = new { Success = false, Message = "Unable to perform action on Accomodation Type." };
            }
            return json;
        }



    }
}

ResortPlay/Areas/Dashboard/Controllers/RolesController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using ResortPlay.Areas.Dashboard.ViewModels;
using ResortPlay.Entity;
using ResortPlay.ViewModels;
using Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ResortPlay.Areas.Dashboard.Controllers
{
    public class RolesController : Controller
    {

        private HMSSignInManager _signInManager;
        private HMSUserManager _userManager;
        private HMSRoleManager _roleManager;


        public HMSSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<HMSSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }
        public HMSUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<HMSUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        public HMSRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<HMSRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }

        }

        public RolesController()
        {
        }

        public RolesController(HMSUserManager userManager, HMSSignInManager signInManager, HMSRoleManager roleManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
            RoleManager = roleManager;
        }


        public ActionResult Index(string searchTerm, int? page)
        {
         
            int recordSize = 10;
            page = page ?? 1;

            RoleListingModel model = new RoleListingModel();
            model.SearchTerm = searchTerm;
            model.Roles = SearchRoles(searchTerm, page.Value, recordSize);
            var totalRecords = SearchRolesCount(searchTerm);
            model.Pager = new Pager(totalRecords, page, recordSize);
            return View(model);
        }
        //Search Users
        public IEnumerable<IdentityRole> SearchRoles(string searchTerm, int page, int recordSize)
        {
            var roles = RoleManager.Roles.AsQueryable();

            if (!string.IsNullOrEmpty(searchTerm))
            {
                roles = roles.Where(a => a.Name.ToLower().Contains(searchTerm.ToLower()));
            }

            var skip = (page - 1) * recordSize;

            return roles.OrderBy(x => x.Name).Skip(skip).Take(recordSize).ToList();
        }
        public int SearchRolesCount(string searchTerm)
        {

            var roles = RoleManager.Roles.AsQueryable();

            if (!string.IsNullOrEmpty(searchTerm))
            {
                roles = roles.Where(a => a.Name.ToLower().Contains(searchTerm.ToLower()));
            }
            return roles.Count();
        }


        [HttpGet]
        public async Task<ActionResult> Action(string Id)
        {
            RoleActionModel model = new RoleActionModel();

            if (!string.IsNullOrEmpty(Id)) // View the records
            {
                var role = await RoleManager.FindByIdAsync(Id);

                model.Id = role.Id;
                model.Name = role.Name;
            }

            return PartialView("_Action", model);
        }
        [HttpPost]
        public async Task<JsonResult> Action(RoleActionModel model)
        {

            JsonResult json = new JsonResult();
            IdentityResult result = null;

            if (!string.IsNullOrEmpty(model.Id)) //Edit a record
            {
                var role = await RoleManager.FindByIdAsync(model.Id);

                role.Name = model.Name;


                result = await RoleManager.UpdateAsync(role);
            }
            else //Create a record
            {

                var role = new IdentityRole();

                role.Name = model.Name;

                result = await RoleManager.CreateAsync(role);
            }

            json.Data = new { Success = result.Succeeded, Message = string.Join(", ", result.Errors) };
            return json;
        }


        [HttpGet]
        public async Task<ActionResult> Delete(string Id)
        {
            RoleActionModel model = new RoleActionModel();

            var role = await RoleManager.FindByIdAsync(Id);

            model.Id = role.Id;

            return PartialView("_Delete", model);

        }
        [HttpPost]
        public async Task<JsonResult> Delete(RoleActionModel model)
        {
            JsonResult json = new JsonResult();
            IdentityResult result = null;

            var role = await RoleManager.FindByIdAsync(model.Id);
            result = await RoleManager.DeleteAsync(role);

            json.Data = new { Success = result.Succeeded, Message = string.Join(", ", result.Errors) };
            return json;
        }
    }
}

ResortPlay/Areas/Dashboard/Controllers/UsersController.cs
using Microsoft.Ajax.Utilities;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using ResortPlay.Areas.Dashboard.ViewModels;
using ResortPlay.Entity;
using ResortPlay.ViewModels;
using Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;

namespace ResortPlay.Areas.Dashboard.Controllers
{
    public class UsersController : Controller
    {

        private HMSSignInManager _signInManager;
        private HMSUserManager _userManager;
        private HMSRoleManager _roleManager;

        public HMSSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<HMSSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }
        public HMSUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<HMSUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        public HMSRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<HMSRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        } 

        public UsersController()
        {
        }

        public UsersController(HMSUserManager userManager, HMSSignInManager signInManager, HMSRoleManager roleManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
            RoleManager = roleManager;
        }

        public async Task<ActionResult> Index(string searchTerm, string roleId, int? page) 
        {
            //how much will show at a time
            int recordSize = 10;
            page = page ?? 1;

            UserListingModel model = new UserListingModel();
            //Word search
            model.SearchTerm = searchTerm;
            model.RoleId = roleId;
            model.Roles = RoleManager.Roles.ToList();

            model.Users = await SearchUsers(searchTerm, roleId, page.Value, recordSize);


            //The pager controller
            var totalRecords = await SearchUsersCount(searchTerm, roleId);
            model.Pager = new Pager(totalRecords, page, recordSize);
            return View(model);
        }
        //Search Users
        public async Task<IEnumerable<HMS_User>> SearchUsers(string searchTerm, string roleId, int page, int recordSize)
        {

            var users = UserManager.Users.AsQueryable();

            if (!string.IsNullOrEmpty(searchTerm))
            {
                users = users.Where(a => a.Email.ToLower().Contains(searchTerm.ToLower()));
            }

            if (!string.IsNullOrEmpty(roleId))
            {
                var role = await RoleManager.FindByIdAsync(roleId);

                var userIds = role.Users.Select(x => x.UserId).ToList();
                users = users.Where(x => userIds.Contains(x.Id));
            }
            var skip = (page - 1) * recordSize;
          

            return users.OrderBy(x => x.Email).Skip(skip).Take(recordSize).ToList();
        }

        public async Task<int> SearchUsersCount(string searchTerm, string roleId)
        {

            var users = UserManager.Users.AsQueryable();

            if (!string.IsNullOrEmpty(searchTerm))
            {
                users = users.Where(a => a.Email.ToLower().Contains(searchTerm.ToLower()));
            }

            if (!string.IsNullOrEmpty(roleId))
            {
                var role = await RoleManager.FindByIdAsync(roleId);

                var userIds = role.Users.Select(x => x.UserId).ToList();
                users = users.Where(x => userIds.Contains(x.Id));
            }
            return users.Count();
        }


        //Here to Read from the model
        [HttpGet]
        public async Task<ActionResult> Action(string Id)
        {
            UserActionModel model = new UserActionModel();

            if (!string.IsNullOrEmpty(Id)) // View the records
            {
                var user = await UserManager.FindByIdAsync(Id);

                model.Id = user.Id;
                model.FullName = user.FullName;
                model.Email = user.Email;
                model.Username = user.UserName;
                model.Country = user.Country;
                model.City = user.City;
                model.Address = user.Address;

            }

            return PartialView("_Action", model);
        }
        //Here to make an action
        [HttpPost]
        public async Task<JsonResult> Action(UserActionModel model)
        {

            JsonResult json = new JsonResult();
            IdentityResult result = null;

            if (!string.IsNullOrEmpty(model.Id)) //Edit a record
            {
                var user = await UserManager.FindByIdAsync(model.Id);

                user.FullName = model.FullName;
                user.Email = model.Email;
                user.UserName = model.Username;

                user.Country = model.Country;
                user.City = model.City;
                user.Address = model.Address;

                result = await UserManager.UpdateAsync(user);
            }
            else //Create a record
            {

                var user = new HMS_User();

                user.FullName = model.FullName;
                user.Email = model.Email;
                user.UserName = model.Username;

                user.Country = model.Country;
                user.City = model.City;
                user.Address = model.Address;

                result = await UserManager.CreateAsync(user);
            }

            json.Data = new { Success = result.Succeeded, Message = string.Join(", ", result.Errors) };
            return json;
        }
        //Here is to Delete the accomodation
        [HttpGet]
        public async Task<ActionResult> Delete(string Id)
        {
            UserActionModel model = new UserActionModel();

            var user = await UserManager.FindByIdAsync(Id);

            model.Id = user.Id;

            return PartialView("_Delete", model);

        }
        [HttpPost]
        public async Task<JsonResult> Delete(UserActionModel model)
        {
            JsonResult json = new JsonResult();
            IdentityResult result = null;

            var user = await UserManager.FindByIdAsync(model.Id);
            result = await UserManager.DeleteAsync(user);

            json.Data = new { Success = result.Succeeded, Message = string.Join(", ", result.Errors) };
            return json;
        }


        //The User Roles Controller. Taking id from the roles and shows the roles
        [HttpGet]
        public async Task<ActionResult> UserRoles(string Id)
        {
            
            UserRolesModel model = new UserRolesModel();

            model.UserId = Id;
            var user = await UserManager.FindByIdAsync(Id);
            var UserRolesIds = user.Roles.Select(x => x.RoleId).ToList();
            model.UserRoles = RoleManager.Roles.Where(x => UserRolesIds.Contains(x.Id)).ToList();

            model.Roles = RoleManager.Roles.Where(x => !UserRolesIds.Contains(x.Id)).ToList();

            return PartialView("_UserRoles", model);
        }
        //Here to make an action
        [HttpPost]
        public async Task<JsonResult> UserRoleOperation(string userId, string roleId, bool isDelete = false)
        {
            JsonResult json = new JsonResult();
            var user = await UserManager.FindByIdAsync(userId);
            var role = await RoleManager.FindByIdAsync(roleId);

            if (user != null && role != null)
            {
                IdentityResult result = null;
                if (!isDelete)
                {
                    result = await UserManager.AddToRoleAsync(userId, role.Name);
                }
                else
                {
                    result = await UserManager.RemoveFromRoleAsync(userId, role.Name);
                }
                
                json.Data = new { Success = result.Succeeded, Message = string.Join(", ", result.Errors)};
            }
            else
            {
                json.Data = new { Success = false, Message = "Invalid operation! " };
            }

            return json;

        }
    }
}

ResortPlay/Areas/Dashboard/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewBag.Title - ResortPlay HMS</title>

    <link rel="icon" type="image/x-icon" href="~/Areas/Dashboard/Content/assets/favicon.ico" />
    <link href="~/Areas/Dashboard/Content/css/styles.css" rel="stylesheet" />

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/Areas/Dashboard/Content/js/scripts.js"></script>
    <script src="https://kit.fontawesome.com/15484bcc60.js" crossorigin="anonymous"></script>

    </head>
<body>
    <div class="d-flex" id="wrapper">
        <!-- Sidebar-->
        <div class="border-end bg-white" id="sidebar-wrapper">
            <div class="sidebar-heading border-bottom bg-light"><i class="fa-solid fa-hotel"></i> ResortPlay HMS</div>
            <div class="list-group list-group-flush">
                <a class="list-group-item list-group-item-action list-group-item-light p-3"
                   href="@Url.Action("Index", "AccomodationTypes")"><i class="fa-solid fa-window-restore"></i> Accomodation Types</a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3"
                   href="@Url.Action("Index", "AccomodationPackages")"><i class="fa-solid fa-network-wired"></i> Accomodation Packages</a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3"
                   href="@Url.Action("Index", "Accomodation")"><i class="fa-solid fa-earth-americas"></i> Accomodations</a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3"
                   href="@Url.Action("Index", "Roles")"><i class="fa-solid fa-users-gear"></i> Roles</a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3"
                   href="@Url.Action("Index", "Users")"><i class="fa-solid fa-user-group"></i> Users</a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3"
                   href="@Url.Action("", "")"><i class="fa-solid fa-wrench"></i> Settings</a>




                <!--Leaving this here for further reference-->
                @*<a class="list-group-item list-group-item-action list-group-item-light p-3" href="#!">Shortcuts</a>
        <a class="list-group-item list-group-item-action list-group-item-light p-3" href="#!">Overview</a>
        <a class="list-group-item list-group-item-action list-group-item-light p-3" href="#!">Events</a>
        <a class="list-group-item list-group-item-action list-group-item-light p-3" href="#!">Profile</a>
        <a class="list-group-item list-group-item-action list-group-item-light p-3" href="#!">Status</a>*@
            </div>
        </div>
        <!-- Page content wrapper-->
        <div id="page-content-wrapper">
            <!-- Top navigation-->
            <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                <div class="container-fluid">
                    <button class="btn btn-primary" id="sidebarToggle"><i class="fa-solid fa-bars"></i></button>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ms-auto mt-2 mt-lg-0">
                            <li class="nav-item active"><a class="nav-link" href="javascript:document.getElementById('logoutForm').submit()">Logout <i class="fa-solid fa-arrow-right-from-bracket"></i></a></li>




                            <!--Leaving this here for further reference-->
                            @*<li class="nav-item"><a class="nav-link" href="#!">Link</a></li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                                    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" href="#!">Action</a>
                                        <a class="dropdown-item" href="#!">Another action</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="#!">Something else here</a>
                                    </div>
                                </li>*@
                        </ul>
                    </div>
                </div>
            </nav>
            <!-- Page content-->
            <div class="container-fluid">
                @RenderBody()
            </div>
        </div>
    </div>

    @using (Html.BeginForm("LogOff", "Account", new { area = "" }, FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
    {
        @Html.AntiForgeryToken()
    }

   
</body>
</html>